### PR TITLE
Created new "paper" layout for walled gardens (and similar future papers) and updated TOC to use auto-generated header links

### PR DESCRIPTION
**Pull request by ssddanbrown**
## Summary of Changes

- Added plugin to generate table-of-contents from auto-generated header links.
- Added filter to clean toc plugin output to remove hash characters.
- Created new "paper" layout for papers such as walled-gardens, which extracts some of the metadata to frontmatter and cleans up the original walled-gardens content to not have so much structural HTML mixed in. This new paper layout can then be re-used by other similar papers.
- Renamed 'static' directory to 'papers' and passed this through to the output content so we can link to papers on the site.
- Removed `isWG` frontmatter variable and instead look-up the layout in use instead of use this variable to drive base template changes.

### CODE REVIEW

**Comment by ssddanbrown** [comment]
This is follow-on work upon a previous couple of PRs as per comment https://github.com/OpenWebAdvocacy/website/pull/19#issuecomment-1098433974  FYI @aliblackwell

**Comment by aliblackwell** [comment]
Superb. Only thing is the original URL for the PDF report is at `/files` ([see report here](https://open-web-advocacy.org/files/OWA%20-%20Bringing%20Competition%20to%20Walled%20Gardens%20-%20v1.0.pdf)) rather than `/papers`. I know we want to preserve the URL as it's in the wild now. We could of course solve this with a 301, but it feels easier to just rename the dir files and pass that through instead?

**Comment by ssddanbrown** [comment]
@aliblackwell Good idea, I've now updated the folder/path.

**Comment by aliblackwell** [comment]
🚀

**Pull request merged**
