### PR TITLE
Update all internal links to point to correct language

### PR DESCRIPTION
**Pull request by jessbudd**
## Related Issue
This PR provides the foundation for resolving https://github.com/OpenWebAdvocacy/website/issues/182. Further PRs to come for full resolution.

## Summary of Changes
The OWA website uses the [Eleventy Internationalisation plugin](https://www.11ty.dev/docs/plugins/i18n/) which requires all internal links to use the `locale_url` filter. This ensures the link includes the relevant language code subdirectory, if that page exists.

- Update homepage (english, spanish and japanese) internal links to use `locale_url` filter 
- Update all partial internal links to use `locale_url` filter 
- Add new `post-meta` partial as the meta is included in two templates. This uses the  `locale_url` filter on post links
- Update base layout to include a `rel=alternate` link for each language for SEO reasons. 
- Add homepage to `/en/` folder and a canonical link to the main homepage. This is to prevent dilution of search ranking due to duplicate content and to enable an automatic detection redirect later
- Add new `englishPostsFilter` filter. This prevents the same blog post being rendered multiple times in different languages. 

## Testing

Vist the preview homepage and confirm the languages alternate links are included in the head. 
Confirm the canonical link only appears on the `/en/` version of the homepage.
Toggle to Spanish on the homepage. Scroll down to the "Get Involved" button in the sidebar. Confirm it correctly links to the Spanish version of the page. (Internal links that do not have a translated page will link to default english page).

image

image

### CODE REVIEW

**Comment by shuuji3** [comment]
I'm not SEO expert but often-referenced Google documentation ([Localized Versions of your Pages | Google Search Central  |  Documentation  |  Google for Developers](https://developers.google.com/search/docs/specialty/international/localized-versions)) recommends using a fully-qualified URL for `<link rel="alternate" ...>` so we should use `href="https://open-web-adovocacy.org/ja/"` etc. instead of `href="/ja/"`.

**Review by sbesh91 — APPROVED** [review]
Big thumbs up from me.  It would make me much more comfortable to have an extra set of eyes beyond my own look at this PR.  @mtom55 or @JamesMooreOWA

**Comment by jessbudd** [comment]
Thanks for that link and your comment @shuuji3! I'll update to use a fully qualified url, and it also looks like we should add a` hreflang="x-default"` for the base english pages as well.

**Comment by jessbudd** [comment]
Have pushed a change to update SEO links to absolute paths and default alternate links 👍

**Comment by shuuji3** [comment]
Thank you, it looks all good now 👍🏻 

Screenshot of HTML having link tag with ref="alternate" and href="(fully qualified URL)" prop

**Comment by mtom55** [comment]
I was just testing, and I'm not sure if this pull request is supposed to cover all of the switching language functionality.  I did find the following issue:
1. visit https://deploy-preview-198--owa-production.netlify.app/
1. Goto "About Us" (or most other pages)
2. Tap the language toggle to switch to Spanish
Expected: Switch to https://deploy-preview-198--owa-production.netlify.app/es/contributors/
Actual: Stays on https://deploy-preview-198--owa-production.netlify.app/contributors/ and language doesn't toggle

and I can't see the message on the the top of the page any more if a page doesn't have a translation?

**Comment by jessbudd** [comment]
Hey @mtom55, no this PR isn't intended to cover all the language switching functionality.  To cover everything would be ~150+ files which I thought would be difficult for reviewing. This PR is only to lay the groundwork for the future PRs. 

If we'd prefer to do it all in one very large PR, let me know and I will add to this one.

**Comment by mtom55** [comment]
No that's fine, I just wanted to check before merging it!  The functionality in this review is not reduced from the functionality that already exists on the site so I think it's fine to merge.

**Pull request merged**
