### PR TITLE
Add basic accessible language switcher dialog

### PR DESCRIPTION
**Pull request by sbesh91**
This PR adds a language switcher dialog to the site.  The emphasis is on making it keyboard and screen reader accessible instead of over-styled.

### CODE REVIEW

**Comment by mtom55** [comment]
Couple of changes:

The selection of languages should be in the original language for each selection
image

or optionally
English / English
Espanol / Spanish

and the 
image
should also be in the language.

and I was thinking if we could add a grey world icon like in the OWA logo to the left of the text.

**Comment by sbesh91** [comment]
> Couple of changes:
> 
> The selection of languages should be in the original language for each selection image
> 
> or optionally English / English Espanol / Spanish
> 
> and the image should also be in the language.
> 
> and I was thinking if we could add a grey world icon like in the OWA logo to the left of the text.

Yeah, I think all of that is reasonable and doable.

**Comment by mtom55** [comment]
I meant more like a globe like https://fontawesome.com/icons/globe?f=classic&s=light (if we can find a royalty free version) rather than the OWA logo, and on the home page rather than the pop-up dialog

**Comment by sbesh91** [comment]
> I meant more like a globe like https://fontawesome.com/icons/globe?f=classic&s=light (if we can find a royalty free version) rather than the OWA logo, and on the home page rather than the pop-up dialog
I understand now.  I'll get that updated.

**Comment by mtom55** [comment]
This page still needs each option in it's original language:
image

i.e. instead of:
English
Spanish

it should be

English
Español.
Languages and close can be in the current language that is set.


image

To the left of the language selector we should also have the icon on the menu:
image

**Comment by mtom55** [comment]
Looks great!

**Pull request merged**
